apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-config
  namespace: prometheus
data:
  config.yml: |-
    global:
      # 当alertmanager持续多长时间未接收到告警后标记告警状态为 resolved
      resolve_timeout: 5m
      # 配置邮件发送信息
      smtp_smarthost: 'smtp.exmail.qq.com:465'
      smtp_from: 'quhui@nbugs.com'
      smtp_auth_username: 'quhui@nbugs.com'
      smtp_auth_password: 'emDzE3PA5dAfgjY7'
      smtp_hello: 'qq.com'
      smtp_require_tls: false
    # 所有报警信息进入后的根路由，用来设置报警的分发策略
    route:
      # 这里的标签列表是接收到报警信息后的重新分组标签，例如，接收到的报警信息里面有许多具有 cluster=A 和 alertname=LatncyHigh 这样的标签的报警信息将会批量被聚合到一个分组里面
      group_by: ['alertname', 'cluster']
      # 当一个新的报警分组被创建后，需要等待至少 group_wait 时间来初始化通知，这种方式可以确保您能有足够的时间为同一分组来获取多个警报，然后一起触发这个报警信息。
      group_wait: 10s

      # 相同的group之间发送告警通知的时间间隔
      group_interval: 30s

      # 如果一个报警信息已经发送成功了，等待 repeat_interval 时间来重新发送他们，不同类型告警发送频率需要具体配置
      repeat_interval: 1m

      # 默认的receiver：如果一个报警没有被一个route匹配，则发送给默认的接收器
      receiver: prometheusalert-base

      # 上面所有的属性都由所有子路由继承，并且可以在每个子路由上进行覆盖。
      routes:
      - receiver: 'p-wx-canal'
        group_wait: 10s
        match:
          app: canal
    receivers:
    - name: 'default'
      email_configs:
      - to: 'horus-k@qq.com'
        send_resolved: true  # 接受告警恢复的通知
    - name: 'prometheusalert-base'
      webhook_configs:
      - url: 'http://prometheus-alert-center.default:8080/prometheusalert?type=wx&tpl=prometheus-wx-base&wxurl=https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=694f0906-fcf1-4f58-b70b-7ae3f0334549'
        send_resolved: true
    - name: 'p-wx-canal'
      webhook_configs:
      - url: 'http://prometheus-alert-center.default:8080/prometheusalert?type=dd&tpl=p-wx-canal&ddurl=https://oapi.dingtalk.com/robot/send?access_token=36de8c44ba098fabb0d22121269749073aa229a376f68d56a431b706d1ad441a'
        send_resolved: true