apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: prometheus
spec:
  type: NodePort
  ports:
    - port: 9090
  selector:
    app: prometheus
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: prometheus
  namespace: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      volumes:
        - name: data
          hostPath:
            path: /data/prometheus-data
        - name: config-volume
          configMap:
            name: prometheus-config
      containers:
        - name: prometheus
          image: 'quay.io/prometheus/prometheus:v2.22.1'
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.retention.time=15d"
            - "--storage.tsdb.path=/prometheus"  # 指定tsdb数据路径
            - "--web.enable-admin-api"  # 控制对admin HTTP API的访问，其中包括删除时间序列等功能
            - "--web.enable-lifecycle"  # 支持热更新，直接执行localhost:9090/-/reload立即生效
          ports:
            - name: web
              containerPort: 9090
              protocol: TCP
          resources:
            limits:
              cpu: '4'
              memory: 5Gi
            requests:
              cpu: 500m
              memory: 2Gi
          volumeMounts:
            - mountPath: "/etc/prometheus"
              name: config-volume
            - mountPath: "/prometheus"
              name: data
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: FallbackToLogsOnError
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 600
      nodeSelector:
        kubernetes.io/hostname: cn-hangzhou.172.16.165.10
      serviceAccountName: prometheus
      securityContext:
        runAsUser: 0
        fsGroup: 0
  revisionHistoryLimit: 10

