apiVersion: v1
kind: Service
metadata:
  name: zk-hs2
  namespace: canal
  labels:
    app: zk2
spec:
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: zk2
---
apiVersion: v1
kind: Service
metadata:
  name: zk-cs2
  namespace: canal
  labels:
    app: zk2
spec:
  ports:
  - port: 2181
    name: client
  selector:
    app: zk2
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: zk-pdb2
  namespace: canal
spec:
  selector:
    matchLabels:
      app: zk2
  maxUnavailable: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk2
  namespace: canal
spec:
  selector:
    matchLabels:
      app: zk2
  serviceName: zk-hs2
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady   #注意这里使用OrderedReady顺序启动方式，Parallel方式可能会报连接错误的问题
  template:
    metadata:
      labels:
        app: zk2
    spec:
      # nodeSelector:
      #   app: app
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution: #软策略
          - weight: 100
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - "zk2"

      containers:
      - name: kubernetes-zookeeper
        imagePullPolicy: Always
        image: "mirrorgcrio/kubernetes-zookeeper:1.0-3.4.10"
        resources: {}
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        command:
        - sh
        - -c
        - "start-zookeeper \
          --servers=3 \
          --data_dir=/var/lib/zookeeper/data \
          --data_log_dir=/var/lib/zookeeper/data/log \
          --conf_dir=/opt/zookeeper/conf \
          --client_port=2181 \
          --election_port=3888 \
          --server_port=2888 \
          --tick_time=2000 \
          --init_limit=10 \
          --sync_limit=5 \
          --heap=512M \
          --max_client_cnxns=60 \
          --snap_retain_count=3 \
          --purge_interval=12 \
          --max_session_timeout=40000 \
          --min_session_timeout=4000 \
          --log_level=INFO"
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "zookeeper-ready 2181"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "zookeeper-ready 2181"
          initialDelaySeconds: 10
          timeoutSeconds: 5