apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    k8s-app: canal-admin
  name: canal-admin-ingress
  namespace: canal
spec:
  rules:
    - host: canal.yalonglee.cn
      http:
        paths:
          - path: /
            backend:
              serviceName: canal-admin
              servicePort: 8089
---
kind: Service
apiVersion: v1
metadata:
  name: canal-admin
  namespace: canal
  labels:
    k8s-app: canal-admin
spec:
  ports:
    - port: 8089
      name: admin-port
  selector:
    k8s-app: canal-admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canal-admin
  namespace: canal
  labels:
    k8s-app: canal-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: canal-admin
  template:
    metadata:
      labels:
        k8s-app: canal-admin
    spec:
      containers:
        - name: canal-admin
          image: registry.cn-hangzhou.aliyuncs.com/nbugs-share/nbugs-canal-admin:v1.1.4
          imagePullPolicy: Always
          env:
            - name: "canal.adminUser"
              value: "admin"
            - name: "canal.adminPasswd"
              value: "admin"
            - name: "server.port"
              value: "8089"
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
          ports:
            - containerPort: 8089
              name: admin-port
      restartPolicy: Always