apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron
  namespace: sentry
  labels:
    app: cron
spec:
  selector:
    matchLabels:
        app: cron
  replicas: 1
  template:
    metadata:
      labels:
        app: cron
    spec:
      containers:
      - name: cron
        image: "registry.cn-hangzhou.aliyuncs.com/nbugs-share/sentry:sentry-onpremise-local"
        imagePullPolicy: IfNotPresent
        command:
          - "/bin/sh"
        args:
          - "-c"
          - exec /docker-entrypoint.sh $0 $@
          - run
          - cron
        ports:
        - containerPort: 9000
        env:
          - name: SENTRY_CONF
            value: '/etc/sentry'
          - name: SNUBA
            value: 'http://snuba-api:1218'
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /etc/sentry
          name: config
        resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: sentry-data
      - name: config
        persistentVolumeClaim:
          claimName: sentry-conf

---
apiVersion: v1
kind: Service
metadata:
  name: cron
  namespace: sentry
spec:
  ports:
    - name: tcp
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: cron
  type: ClusterIP