apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentry-cleanup
  namespace: sentry
  labels:
    app: sentry-cleanup
spec:
  selector:
    matchLabels:
        app: sentry-cleanup
  replicas: 1
  template:
    metadata:
      labels:
        app: sentry-cleanup
    spec:
      containers:
      - name: sentry-cleanup
        image: "registry.cn-hangzhou.aliyuncs.com/nbugs-share/sentry:sentry-cleanup-onpremise-local"
        imagePullPolicy: IfNotPresent
        command:
          - "/entrypoint.sh"
        args:
          - "0 0 * * * gosu sentry sentry cleanup --days $SENTRY_EVENT_RETENTION_DAYS"
        ports:
        - containerPort: 9000
        env:
          - name: SENTRY_CONF
            value: '/etc/sentry'
          - name: SNUBA
            value: 'http://snuba-api:1218'
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /etc/sentry
          name: config
        resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: sentry-data
      - name: config
        persistentVolumeClaim:
          claimName: sentry-conf
---
apiVersion: v1
kind: Service
metadata:
  name: sentry-cleanup
  namespace: sentry
spec:
  ports:
    - name: tcp
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: sentry-cleanup
  type: ClusterIP