apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: sentry
  labels:
    app: web
spec:
  selector:
    matchLabels:
        app: web
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: "registry.cn-hangzhou.aliyuncs.com/nbugs-share/sentry:sentry-onpremise-local"
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -c
          - 'exec /docker-entrypoint.sh $0 $@'
        args:
          - run
          - web
        ports:
        - containerPort: 9000
        env:
          - name: SENTRY_CONF
            value: '/etc/sentry'
          - name: SNUBA
            value: 'http://snuba-api:1218'
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /etc/sentry
          name: config
        readinessProbe:
          tcpSocket:
            port: 9000
          periodSeconds: 5
          timeoutSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 9000
          periodSeconds: 5
          timeoutSeconds: 5
        startupProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 10
          failureThreshold: 15
          periodSeconds: 5
          timeoutSeconds: 10

        resources:
            limits:
              cpu: '2'
              memory: 1024Mi
            requests:
              cpu: 10m
              memory: 1024Mi
      - name: relay
        image: "registry-vpc.cn-hangzhou.aliyuncs.com/nbugs-share/sentry:relay-local-1"
        imagePullPolicy: Always
        command:
          - "/bin/bash"
        args:
          - /docker-entrypoint.sh
          - run
        ports:
        - containerPort: 3000
        # volumeMounts:
        # - mountPath: /work/.relay
        #   name: relay
        resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 10m
              memory: 300Mi
      - name: api
        image: "getsentry/snuba:20.8.0"
        imagePullPolicy: IfNotPresent
        command:
          - "/usr/src/snuba/docker_entrypoint.sh"
        args:
          - api
        ports:
          - containerPort: 1218
        env:
          - name: SNUBA_SETTINGS
            value: docker
          - name: CLICKHOUSE_HOST
            value: clickhouse
          - name: DEFAULT_BROKERS
            valueFrom:
              configMapKeyRef:
                name: sentry-conf
                key: kafka-host
          - name: REDIS_HOST
            value: redis
          - name: UWSGI_MAX_REQUESTS
            value: '10000'
          - name: UWSGI_DISABLE_LOGGING
            value: 'true'
        resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 512Mi
      - name: nginx
        image: "nginx:1.16"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx
          name: config-nginx
          readOnly: true
        resources:
            limits:
              cpu: 1000m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi


      
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: sentry-data
      - name: config
        persistentVolumeClaim:
          claimName: sentry-conf
      - name: config-nginx
        persistentVolumeClaim:
          claimName: nbugs-nginx

---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: sentry
spec:
  ports:
    - name: tcp
      port: 9000
      protocol: TCP
      targetPort: 9000
  clusterIP: None
  selector:
    app: web
  type: ClusterIP