apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: sentry
  labels:
    app: worker
spec:
  selector:
    matchLabels:
        app: worker
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: "registry.cn-hangzhou.aliyuncs.com/nbugs-share/sentry:sentry-onpremise-local"
        imagePullPolicy: IfNotPresent
        command:
          - "/bin/sh"
        args:
          - "-c"
          - 'exec /docker-entrypoint.sh $0 $@'
          - run
          - worker
        ports:
        - containerPort: 9000
        env:
          - name: SENTRY_CONF
            value: '/etc/sentry'
          - name: SNUBA
            value: 'http://snuba-api:1218'
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /etc/sentry
          name: config
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 500m
            memory: 1024Mi
        readinessProbe:
          tcpSocket:
            port: 9000
          periodSeconds: 5
          timeoutSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 9000
          periodSeconds: 5
          timeoutSeconds: 5
        startupProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 10
          failureThreshold: 15
          periodSeconds: 5
          timeoutSeconds: 10
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: sentry-data
      - name: config
        persistentVolumeClaim:
          claimName: sentry-conf
---
apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: sentry
spec:
  ports:
    - name: tcp
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: worker
  type: ClusterIP