apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-manager
  namespace: devops
  labels:
    app: kafka-manager
spec:
  selector:
    matchLabels:
        app: kafka-manager
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-manager
    spec:
      containers:
      - name: sentry-nginx
        image: "registry.cn-hangzhou.aliyuncs.com/nbugs-share/share:kafka-manager"
        command:
          - java
          - -jar
          - /app.jar
          - --spring.config.location=/application.yml
        ports:
        - containerPort: 8080
        resources:
            limits:
              cpu: '2'
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 1024Mi