apiVersion: apps/v1
kind: Deployment
metadata:
  name: nbugs-sentry-metrics
  labels:
    app: nbugs-sentry
    chart: "sentry-4.3.3"
    release: "nbugs-sentry"
    heritage: "Helm"
spec:
  selector:
    matchLabels:
        app: nbugs-sentry
        release: "nbugs-sentry"
        role: metrics
  template:
    metadata:
      labels:
        app: nbugs-sentry
        release: "nbugs-sentry"
        role: metrics
    spec:
      containers:
      - name: sentry-metrics
        args: 
          - "--statsd.listen-udp=:9125"
          - "--web.listen-address=:9102"
        image: "prom/statsd-exporter:v0.10.5"
        imagePullPolicy: IfNotPresent
        ports:
        - name: statsd
          containerPort: 9125
        - name: metrics
          containerPort: 9102
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9102
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9102
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi