kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nbugs-sentry
  labels:
    app: nbugs-sentry
    chart: "sentry-4.3.3"
    release: "nbugs-sentry"
    heritage: "Helm"
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "10Gi"
  storageClassName: "ali-nas-subpath"