kind: Deployment
apiVersion: apps/v1
metadata:
  name: batch-import-dev
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos-dev
  strategy:
    type: recreate
  template:
    metadata:
      labels:
        app: nacos-dev
    spec:
      containers:
        - name: nacos
          image: >-
            nacos/nacos-server:2.0.1
          ports:
            - name: tcp
              containerPort: 8848
              protocol: TCP
          env:
            - name: MODE
              value: standalone
            
          resources:
            limits:
              cpu: '2'
              memory: 1500Mi
            requests:
              cpu: 100m
              memory: 1500Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 2
            failureThreshold: 5
          imagePullPolicy: Always
