#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: jenkins-pv
#spec:
#  capacity:
#    storage: 5Gi
#  accessModes:
#  - ReadWriteMany
#  persistentVolumeReclaimPolicy: Delete
#  nfs:
#    server: 192.168.0.177
#    path: /data/k8s/jenkins
#
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: jenkins-pvc
#  namespace: devops
#spec:
#  accessModes:
#  - ReadWriteMany
#  resources:
#    requests:
#      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: devops
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client-storageclass"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
